# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket          = "bloxico-backend-grunt"
    dynamo_db_table = "my_lock_table"
    encrypt         = true
    key             = "frontend-app/terraform.tfstate"
    region          = "eu-central-1"
  }
}
